# Copy this file to scripts/dev/local_paths.sh and edit the paths for your machine.
# scripts/dev/activate_glls.sh loads local_paths.sh before applying defaults.

# Main external workspace. Datasets, checkpoints, graph caches, and runtime
# outputs can all live here.
export GLLS_DATA_ROOT="${HOME}/data/GLLS"

GLLS_LOCAL_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GLLS_LOCAL_PROJECT_ROOT="$(cd "${GLLS_LOCAL_SCRIPT_DIR}/../.." && pwd)"

# MMAD-style QA datasets. This folder should contain DS-MVTec/ and VisA/.
export GLLS_DATASET_ROOT="${GLLS_DATA_ROOT}/datasets/MMAD"

# Curated QA annotations shipped with this repository.
export GLLS_QA_ROOT="${GLLS_LOCAL_PROJECT_ROOT}/qa_collection"

# PVLA/RAG graph cache root generated by python -m glls.rag.build_graph.
export GLLS_GRAPH_CACHE_ROOT="${GLLS_DATA_ROOT}/databases/graph_index"

# VLM and method checkpoints.
export GLLS_VLM_MODEL_PATH="${GLLS_DATA_ROOT}/models/qwen3-vl-8B"
export GLLS_SAM3_PATH="${GLLS_DATA_ROOT}/models/sam3/sam3.pt"
export GLLS_ADAPTCLIP_ROOT="${GLLS_DATA_ROOT}/models/AdaptCLIP"
export GLLS_EMBEDDING_MODEL_PATH="${GLLS_DATA_ROOT}/models/bge-base-en-v1.5"

# Optional binary AD datasets.
export GLLS_MPDD_ROOT="${GLLS_DATA_ROOT}/datasets/MPDD"
export GLLS_DTD_ROOT="${GLLS_DATA_ROOT}/datasets/DTD"
export GLLS_DAGM_ROOT="${GLLS_DATA_ROOT}/datasets/DAGM_KaggleUpload"

# Python environment used by helper scripts.
export GLLS_VENV="${GLLS_DATA_ROOT}/envs/GLLS"
